# Generated by Django 3.2.8 on 2021-11-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pos_neg_rate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
