# Generated by Django 3.2.8 on 2021-11-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_productmodel_pos_neg_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='date',
            field=models.CharField(default='', max_length=256),
        ),
    ]
